[features]
seeds = false
skip-lint = false
[programs.localnet]
myfirstproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/cheyo/.config/solana/id.json"

[scripts]
test = "node tests/myfirstproject.js"
